"""add_exercises_and_test_cases

Revision ID: 20aed03ca27b
Revises: 83f3f88a382a
Create Date: 2026-06-08 12:34:14.334286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20aed03ca27b'
down_revision: Union[str, Sequence[str], None] = '83f3f88a382a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('title', sa.String(length=255), nullable=False, comment='题目标题'),
    sa.Column('description', sa.Text(), nullable=False, comment='题目描述（Markdown）'),
    sa.Column('difficulty', sa.Integer(), nullable=False, comment='难度 1-5（1=非常简单, 5=挑战）'),
    sa.Column('concepts', sa.String(length=500), nullable=True, comment='关联知识点，逗号分隔（如 for_loop,list）'),
    sa.Column('learning_objective', sa.String(length=500), nullable=True, comment='教学目标（学生完成后应掌握什么）'),
    sa.Column('example_input', sa.Text(), nullable=True, comment='示例输入'),
    sa.Column('example_output', sa.Text(), nullable=True, comment='示例输出'),
    sa.Column('reference_solution', sa.Text(), nullable=True, comment='参考解法（仅教师/AI 可见）'),
    sa.Column('source', sa.String(length=20), nullable=False, comment='来源：ai_generated | teacher_created'),
    sa.Column('is_published', sa.Boolean(), nullable=False, comment='是否发布（草稿不可见）'),
    sa.Column('use_count', sa.Integer(), nullable=False, comment='被使用的次数'),
    sa.Column('pass_rate', sa.Float(), nullable=True, comment='通过率（0-1）'),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_id'), 'exercises', ['id'], unique=False)
    op.create_table('test_cases',
    sa.Column('exercise_id', sa.String(), nullable=False),
    sa.Column('input_data', sa.Text(), nullable=True, comment='标准输入'),
    sa.Column('expected_output', sa.Text(), nullable=False, comment='期望输出'),
    sa.Column('is_hidden', sa.Boolean(), nullable=False, comment='是否隐藏（学生不可见）'),
    sa.Column('description', sa.String(length=255), nullable=True, comment="测试用例描述（如 '测试空列表'）"),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_cases_exercise_id'), 'test_cases', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_test_cases_id'), 'test_cases', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_cases_id'), table_name='test_cases')
    op.drop_index(op.f('ix_test_cases_exercise_id'), table_name='test_cases')
    op.drop_table('test_cases')
    op.drop_index(op.f('ix_exercises_id'), table_name='exercises')
    op.drop_table('exercises')
    # ### end Alembic commands ###
