"""add_student_profiles

Revision ID: 46acb4dc48ae
Revises: 20aed03ca27b
Create Date: 2026-06-08 12:35:19.814051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46acb4dc48ae'
down_revision: Union[str, Sequence[str], None] = '20aed03ca27b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_events',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False, comment='事件类型：question_asked | code_submitted | exercise_passed | exercise_failed | hint_requested | concept_viewed | syntax_error | runtime_error'),
    sa.Column('concept', sa.String(length=100), nullable=True, comment='关联知识点'),
    sa.Column('detail_json', sa.Text(), nullable=True, comment='事件详情（JSON）'),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_events_id'), 'learning_events', ['id'], unique=False)
    op.create_index(op.f('ix_learning_events_user_id'), 'learning_events', ['user_id'], unique=False)
    op.create_table('student_profiles',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False, comment='当前学习等级 1-10'),
    sa.Column('total_exercises_completed', sa.Integer(), nullable=False),
    sa.Column('total_exercises_passed', sa.Integer(), nullable=False),
    sa.Column('total_code_submissions', sa.Integer(), nullable=False),
    sa.Column('total_chat_messages', sa.Integer(), nullable=False),
    sa.Column('total_hints_used', sa.Integer(), nullable=False),
    sa.Column('concept_mastery_json', sa.Text(), nullable=True),
    sa.Column('recommended_concept', sa.String(length=100), nullable=True, comment='推荐的下一知识点'),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_profiles_id'), 'student_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_student_profiles_user_id'), 'student_profiles', ['user_id'], unique=True)
    op.create_table('student_weaknesses',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('concept', sa.String(length=100), nullable=False, comment='知识点标识'),
    sa.Column('fail_count', sa.Integer(), nullable=False, comment='连续失败次数'),
    sa.Column('last_error_type', sa.String(length=100), nullable=True, comment='最后一次的错误类型'),
    sa.Column('severity', sa.Integer(), nullable=False, comment='严重程度 1-5（5=最薄弱）'),
    sa.Column('is_resolved', sa.Boolean(), nullable=False, comment='是否已解决'),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_weaknesses_id'), 'student_weaknesses', ['id'], unique=False)
    op.create_index(op.f('ix_student_weaknesses_user_id'), 'student_weaknesses', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_weaknesses_user_id'), table_name='student_weaknesses')
    op.drop_index(op.f('ix_student_weaknesses_id'), table_name='student_weaknesses')
    op.drop_table('student_weaknesses')
    op.drop_index(op.f('ix_student_profiles_user_id'), table_name='student_profiles')
    op.drop_index(op.f('ix_student_profiles_id'), table_name='student_profiles')
    op.drop_table('student_profiles')
    op.drop_index(op.f('ix_learning_events_user_id'), table_name='learning_events')
    op.drop_index(op.f('ix_learning_events_id'), table_name='learning_events')
    op.drop_table('learning_events')
    # ### end Alembic commands ###
