"""add_rag_documents_and_chunks

Revision ID: 72cac29d4848
Revises: abd7ed27c40e
Create Date: 2026-06-08 02:44:31.429074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72cac29d4848'
down_revision: Union[str, Sequence[str], None] = 'abd7ed27c40e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_documents',
    sa.Column('title', sa.String(length=255), nullable=False, comment='文档标题'),
    sa.Column('source_type', sa.String(length=50), nullable=False, comment='来源类型：manual | uploaded | generated'),
    sa.Column('content', sa.Text(), nullable=False, comment='文档原始内容（Markdown 格式）'),
    sa.Column('difficulty', sa.String(length=20), nullable=False, comment='难度：beginner | intermediate | advanced'),
    sa.Column('concepts', sa.String(length=500), nullable=True, comment='关联知识点，逗号分隔（如 variables,data_types）'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用（禁用后不再参与检索）'),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_documents_id'), 'rag_documents', ['id'], unique=False)
    op.create_table('rag_chunks',
    sa.Column('document_id', sa.String(), nullable=False, comment='所属文档 ID'),
    sa.Column('chunk_index', sa.Integer(), nullable=False, comment='在文档中的顺序索引'),
    sa.Column('content', sa.Text(), nullable=False, comment='片段文本内容'),
    sa.Column('heading', sa.String(length=255), nullable=True, comment="所属章节标题（如 '## 列表的基本操作'）"),
    sa.Column('tokens', sa.Text(), nullable=True, comment='分词后的 tokens（空格分隔），用于关键词检索'),
    sa.Column('difficulty', sa.String(length=20), nullable=False, comment='难度级别'),
    sa.Column('concepts', sa.String(length=500), nullable=True, comment='关联知识点标签'),
    sa.Column('retrieval_count', sa.Integer(), nullable=False, comment='被检索到的次数'),
    sa.Column('use_count', sa.Integer(), nullable=False, comment='被实际用于生成回答的次数'),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['rag_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_chunks_document_id'), 'rag_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_rag_chunks_id'), 'rag_chunks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rag_chunks_id'), table_name='rag_chunks')
    op.drop_index(op.f('ix_rag_chunks_document_id'), table_name='rag_chunks')
    op.drop_table('rag_chunks')
    op.drop_index(op.f('ix_rag_documents_id'), table_name='rag_documents')
    op.drop_table('rag_documents')
    # ### end Alembic commands ###
