"""add_chat_sessions_and_messages

Revision ID: abd7ed27c40e
Revises: 6ff616aeec07
Create Date: 2026-06-08 02:29:05.689877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abd7ed27c40e'
down_revision: Union[str, Sequence[str], None] = '6ff616aeec07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('student_id', sa.String(), nullable=False, comment='所属学生 ID'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='会话标题'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='会话是否活跃（学生可手动关闭）'),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_id'), 'chat_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_student_id'), 'chat_sessions', ['student_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('session_id', sa.String(), nullable=False, comment='所属会话 ID'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='消息角色：user | assistant | system'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容（文本或 JSON 字符串）'),
    sa.Column('response_type', sa.String(length=50), nullable=True, comment='AI 回复类型：concept_explanation | code_feedback | hint | exercise | general'),
    sa.Column('hint_level', sa.Integer(), nullable=True, comment='提示等级 1-5（仅 assistant 消息）'),
    sa.Column('related_concepts', sa.String(length=500), nullable=True, comment='关联知识点，逗号分隔'),
    sa.Column('next_action', sa.String(length=50), nullable=True, comment='建议下一步：try_exercise | read_concept | ask_question | try_again'),
    sa.Column('token_count', sa.Integer(), nullable=True, comment='本次消息消耗的 token 数（仅 assistant）'),
    sa.Column('metadata_json', sa.Text(), nullable=True, comment='额外元数据（JSON）：如引用的 RAG chunk IDs、使用的 Prompt 版本等'),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_chat_sessions_student_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
