"""add_prompt_templates

Revision ID: afc8d011c8ae
Revises: 46acb4dc48ae
Create Date: 2026-06-08 14:58:32.018154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afc8d011c8ae'
down_revision: Union[str, Sequence[str], None] = '46acb4dc48ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_templates',
    sa.Column('name', sa.String(length=100), nullable=False, comment='模板名称（如 tutor_system_prompt）'),
    sa.Column('version', sa.Integer(), nullable=False, comment='版本号'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='分类：teaching | code_review | exercise | safety | general'),
    sa.Column('content', sa.Text(), nullable=False, comment='Prompt 内容'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='版本变更说明'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否当前使用版本'),
    sa.Column('created_by', sa.String(), nullable=True, comment='修改者'),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_templates_id'), 'prompt_templates', ['id'], unique=False)
    op.create_index(op.f('ix_prompt_templates_name'), 'prompt_templates', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompt_templates_name'), table_name='prompt_templates')
    op.drop_index(op.f('ix_prompt_templates_id'), table_name='prompt_templates')
    op.drop_table('prompt_templates')
    # ### end Alembic commands ###
